[INFO] 2025-09-13 16:46:06,519 movies.management.commands.import_movies | Starting movies import from C:\Users\vyshn\movie_recommender\movie_recommender\data\movies.csv...
[INFO] 2025-09-13 16:46:40,609 movies.management.commands.import_movies | Starting ratings import from C:\Users\vyshn\movie_recommender\movie_recommender\data\ratings.csv...
[INFO] 2025-09-13 16:56:57,967 movies.management.commands.import_movies | Starting movies import from C:\Users\vyshn\movie_recommender\movie_recommender\data\movies.csv...
[INFO] 2025-09-13 16:57:34,548 movies.management.commands.import_movies | Starting ratings import from C:\Users\vyshn\movie_recommender\movie_recommender\data\ratings.csv...
[INFO] 2025-09-13 17:02:12,816 movies.management.commands.import_movies | Starting movies import from C:\Users\vyshn\movie_recommender\movie_recommender\data\movies.csv...
[INFO] 2025-09-13 17:02:49,139 movies.management.commands.import_movies | Starting ratings import from C:\Users\vyshn\movie_recommender\movie_recommender\data\ratings.csv...
[INFO] 2025-09-19 21:01:26,672 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:02:01,080 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:02:48,278 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\urls.py changed, reloading.
[INFO] 2025-09-19 21:02:48,821 django.utils.autoreload | Watching for file changes with StatReloader
[WARNING] 2025-09-19 21:03:38,565 django.request | Not Found: /api
[WARNING] 2025-09-19 21:03:38,566 django.server | "GET /api HTTP/1.1" 404 2704
[WARNING] 2025-09-19 21:03:42,388 django.request | Unsupported Media Type: /api/token/
[WARNING] 2025-09-19 21:03:42,389 django.server | "POST /api/token/ HTTP/1.1" 415 62
[WARNING] 2025-09-19 21:03:51,498 django.request | Unsupported Media Type: /api/token/
[WARNING] 2025-09-19 21:03:51,499 django.server | "POST /api/token/ HTTP/1.1" 415 62
[WARNING] 2025-09-19 21:03:53,653 django.request | Unsupported Media Type: /api/token/
[WARNING] 2025-09-19 21:03:53,654 django.server | "POST /api/token/ HTTP/1.1" 415 62
[WARNING] 2025-09-19 21:04:41,094 django.request | Bad Request: /api/token/
[WARNING] 2025-09-19 21:04:41,094 django.server | "POST /api/token/ HTTP/1.1" 400 79
[WARNING] 2025-09-19 21:05:24,881 django.request | Unauthorized: /api/token/
[WARNING] 2025-09-19 21:05:24,882 django.server | "POST /api/token/ HTTP/1.1" 401 63
[INFO] 2025-09-19 21:05:52,317 django.server | "GET /admin/ HTTP/1.1" 302 0
[INFO] 2025-09-19 21:05:52,624 django.server | "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4173
[INFO] 2025-09-19 21:05:53,026 django.server | "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
[INFO] 2025-09-19 21:05:53,041 django.server | "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
[INFO] 2025-09-19 21:05:53,094 django.server | "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
[INFO] 2025-09-19 21:05:53,098 django.server | "GET /static/admin/css/login.css HTTP/1.1" 200 951
[INFO] 2025-09-19 21:05:53,100 django.server | "GET /static/admin/css/base.css HTTP/1.1" 200 22120
[INFO] 2025-09-19 21:05:53,108 django.server | "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
[INFO] 2025-09-19 21:05:53,137 django.server | "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
[WARNING] 2025-09-19 21:05:53,150 django.request | Not Found: /favicon.ico
[WARNING] 2025-09-19 21:05:53,151 django.server | "GET /favicon.ico HTTP/1.1" 404 2728
[INFO] 2025-09-19 21:05:57,302 django.server | "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4348
[INFO] 2025-09-19 21:06:09,480 django.server | "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4344
[INFO] 2025-09-19 21:06:22,424 django.server | "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4344
[INFO] 2025-09-19 21:06:33,206 django.server | "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4344
[INFO] 2025-09-19 21:13:58,516 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:14:02,495 django.server | "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4173
[INFO] 2025-09-19 21:14:05,529 django.server | "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4348
[INFO] 2025-09-19 21:14:18,619 django.server | "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[INFO] 2025-09-19 21:14:18,708 django.server | "GET /admin/ HTTP/1.1" 200 8998
[INFO] 2025-09-19 21:14:18,791 django.server | "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[INFO] 2025-09-19 21:14:18,906 django.server | "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
[INFO] 2025-09-19 21:14:18,921 django.server | "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[INFO] 2025-09-19 21:14:26,451 django.server | "GET /admin/auth/user/add/ HTTP/1.1" 200 14192
[INFO] 2025-09-19 21:14:26,473 django.server | "GET /static/admin/css/forms.css HTTP/1.1" 200 8525
[INFO] 2025-09-19 21:14:26,477 django.server | "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[INFO] 2025-09-19 21:14:26,479 django.server | "GET /static/admin/css/unusable_password_field.css HTTP/1.1" 200 663
[INFO] 2025-09-19 21:14:26,490 django.server | "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[INFO] 2025-09-19 21:14:26,492 django.server | "GET /static/admin/css/widgets.css HTTP/1.1" 200 11991
[INFO] 2025-09-19 21:14:26,497 django.server | "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
[INFO] 2025-09-19 21:14:26,499 django.server | "GET /static/admin/js/core.js HTTP/1.1" 200 6208
[INFO] 2025-09-19 21:14:26,505 django.server | "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
[INFO] 2025-09-19 21:14:26,508 django.server | "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[INFO] 2025-09-19 21:14:26,509 django.server | "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
[INFO] 2025-09-19 21:14:26,514 django.server | "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
[INFO] 2025-09-19 21:14:26,518 django.server | "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
[INFO] 2025-09-19 21:14:26,546 django.server | "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[INFO] 2025-09-19 21:14:26,562 django.server | "GET /static/admin/js/unusable_password_field.js HTTP/1.1" 200 1480
[INFO] 2025-09-19 21:14:26,572 django.server | "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
[INFO] 2025-09-19 21:14:46,490 django.server | "POST /admin/auth/user/add/ HTTP/1.1" 302 0
[INFO] 2025-09-19 21:14:46,691 django.server | "GET /admin/auth/user/278/change/ HTTP/1.1" 200 24964
[INFO] 2025-09-19 21:14:46,711 django.server | "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[INFO] 2025-09-19 21:14:46,728 django.server | "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
[INFO] 2025-09-19 21:14:46,729 django.server | "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
[INFO] 2025-09-19 21:14:46,730 django.server | "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15845
[INFO] 2025-09-19 21:14:46,730 django.server | "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
[INFO] 2025-09-19 21:14:46,747 django.server | "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[INFO] 2025-09-19 21:14:46,765 django.server | "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[INFO] 2025-09-19 21:14:46,765 django.server | "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[INFO] 2025-09-19 21:14:46,766 django.server | "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
[INFO] 2025-09-19 21:14:46,767 django.server | "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[INFO] 2025-09-19 21:15:00,589 django.server | "POST /api/token/ HTTP/1.1" 200 494
[INFO] 2025-09-19 21:18:48,331 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movie_recommender\settings.py changed, reloading.
[INFO] 2025-09-19 21:18:48,927 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:34:04,207 django.server | "GET /admin HTTP/1.1" 301 0
[INFO] 2025-09-19 21:34:04,332 django.server | "GET /admin/ HTTP/1.1" 200 9372
[WARNING] 2025-09-19 21:34:13,638 django.request | Not Found: /movies/
[WARNING] 2025-09-19 21:34:13,639 django.server | "GET /movies/?genre=Action HTTP/1.1" 404 2729
[INFO] 2025-09-19 21:35:17,041 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\urls.py changed, reloading.
[INFO] 2025-09-19 21:35:17,600 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:36:05,451 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\views.py changed, reloading.
[INFO] 2025-09-19 21:36:06,039 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:37:13,201 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:38:19,739 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:38:42,206 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\views.py changed, reloading.
[INFO] 2025-09-19 21:38:42,754 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:38:50,254 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:39:47,513 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\views.py changed, reloading.
[INFO] 2025-09-19 21:39:48,104 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:39:59,256 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:41:12,450 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\views.py changed, reloading.
[INFO] 2025-09-19 21:41:12,977 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:44:12,653 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:45:32,697 django.utils.autoreload | Watching for file changes with StatReloader
[WARNING] 2025-09-19 21:45:46,625 django.request | Not Found: /movies/
[WARNING] 2025-09-19 21:45:46,626 django.server | "GET /movies/?genre=Action HTTP/1.1" 404 2729
[INFO] 2025-09-19 21:46:01,912 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movie_recommender\urls.py changed, reloading.
[INFO] 2025-09-19 21:46:02,433 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:46:06,818 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\urls.py changed, reloading.
[INFO] 2025-09-19 21:46:07,319 django.utils.autoreload | Watching for file changes with StatReloader
[WARNING] 2025-09-19 21:46:12,609 django.request | Not Found: /movies/
[WARNING] 2025-09-19 21:46:12,610 django.server | "GET /movies/?genre=Action HTTP/1.1" 404 2729
[ERROR] 2025-09-19 21:46:47,574 django.request | Internal Server Error: /api/movies/
Traceback (most recent call last):
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\generics.py", line 154, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 66, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 18, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 49, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
    ...<2 lines>...
            fields = filterset_fields
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\filterset.py", line 82, in __new__
    new_class.base_filters = new_class.get_filters()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\filterset.py", line 371, in get_filters
    raise TypeError(
    ...<2 lines>...
    )
TypeError: 'Meta.fields' must not contain non-model field names: genre, release_year
[ERROR] 2025-09-19 21:46:47,586 django.server | "GET /api/movies/?genre=Action HTTP/1.1" 500 130221
[INFO] 2025-09-19 21:47:35,354 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\views.py changed, reloading.
[INFO] 2025-09-19 21:47:35,915 django.utils.autoreload | Watching for file changes with StatReloader
[ERROR] 2025-09-19 21:47:38,484 django.request | Internal Server Error: /api/movies/
Traceback (most recent call last):
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\generics.py", line 154, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 66, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 18, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 49, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
    ...<2 lines>...
            fields = filterset_fields
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\filterset.py", line 82, in __new__
    new_class.base_filters = new_class.get_filters()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\filterset.py", line 371, in get_filters
    raise TypeError(
    ...<2 lines>...
    )
TypeError: 'Meta.fields' must not contain non-model field names: release_year
[ERROR] 2025-09-19 21:47:38,487 django.server | "GET /api/movies/?genre=Action HTTP/1.1" 500 130640
[INFO] 2025-09-19 21:48:11,698 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\serializers.py changed, reloading.
[INFO] 2025-09-19 21:48:12,263 django.utils.autoreload | Watching for file changes with StatReloader
[ERROR] 2025-09-19 21:48:14,615 django.request | Internal Server Error: /api/movies/
Traceback (most recent call last):
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\generics.py", line 154, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 66, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 18, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 49, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
    ...<2 lines>...
            fields = filterset_fields
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\filterset.py", line 82, in __new__
    new_class.base_filters = new_class.get_filters()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\filterset.py", line 371, in get_filters
    raise TypeError(
    ...<2 lines>...
    )
TypeError: 'Meta.fields' must not contain non-model field names: release_year
[ERROR] 2025-09-19 21:48:14,619 django.server | "GET /api/movies/?genre=Action HTTP/1.1" 500 130640
[ERROR] 2025-09-19 21:48:18,026 django.request | Internal Server Error: /api/movies/
Traceback (most recent call last):
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\generics.py", line 203, in get
    return self.list(request, *args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\rest_framework\generics.py", line 154, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 66, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 18, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\rest_framework\backends.py", line 49, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
    ...<2 lines>...
            fields = filterset_fields
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\filterset.py", line 82, in __new__
    new_class.base_filters = new_class.get_filters()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\vyshn\movie_recommender\env\Lib\site-packages\django_filters\filterset.py", line 371, in get_filters
    raise TypeError(
    ...<2 lines>...
    )
TypeError: 'Meta.fields' must not contain non-model field names: release_year
[ERROR] 2025-09-19 21:48:18,029 django.server | "GET /api/movies/?genre=Action HTTP/1.1" 500 130640
[INFO] 2025-09-19 21:49:08,264 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\views.py changed, reloading.
[INFO] 2025-09-19 21:49:08,820 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-19 21:49:16,182 django.server | "GET /api/movies/?genre=Action HTTP/1.1" 200 1009
[INFO] 2025-09-19 21:52:02,876 django.server | "GET //api/movies/?search=dark HTTP/1.1" 200 1008
[INFO] 2025-09-19 21:52:38,267 django.server | "GET //api/movies/?ordering=-release_year HTTP/1.1" 200 1019
[INFO] 2025-09-19 21:53:07,838 django.server | "GET //api/movies/?ordering=-release_date HTTP/1.1" 200 1019
[INFO] 2025-09-19 21:53:35,399 django.server | "GET //api/movies/?genre=comedy HTTP/1.1" 200 1009
[INFO] 2025-09-19 21:53:51,981 django.server | "GET //api/movies/?genres=comedy HTTP/1.1" 200 927
[INFO] 2025-09-20 22:15:40,839 django.utils.autoreload | Watching for file changes with StatReloader
[WARNING] 2025-09-20 22:17:32,241 django.request | Not Found: /
[WARNING] 2025-09-20 22:17:32,242 django.server | "GET / HTTP/1.1" 404 2677
[WARNING] 2025-09-20 22:17:32,317 django.request | Not Found: /favicon.ico
[WARNING] 2025-09-20 22:17:32,317 django.server | "GET /favicon.ico HTTP/1.1" 404 2728
[INFO] 2025-09-20 22:17:42,697 django.server | "GET /api/movies/1 HTTP/1.1" 301 0
[INFO] 2025-09-20 22:17:42,729 django.server | "GET /api/movies/1/ HTTP/1.1" 200 110
[WARNING] 2025-09-20 22:17:50,115 django.request | Not Found: /api/movies/2//
[WARNING] 2025-09-20 22:17:50,116 django.server | "GET /api/movies/2// HTTP/1.1" 404 3133
[INFO] 2025-09-20 22:17:53,098 django.server | "GET /api/movies/2/ HTTP/1.1" 200 91
[INFO] 2025-09-20 22:51:13,176 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\serializers.py changed, reloading.
[INFO] 2025-09-20 22:51:14,237 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-20 22:52:00,995 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\urls.py changed, reloading.
[INFO] 2025-09-20 22:52:02,173 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-20 22:53:30,460 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\views.py changed, reloading.
[INFO] 2025-09-20 22:53:31,639 django.utils.autoreload | Watching for file changes with StatReloader
[WARNING] 2025-09-20 22:53:39,813 django.request | Not Found: /api/
[WARNING] 2025-09-20 22:53:39,815 django.server | "GET /api/ HTTP/1.1" 404 3918
[INFO] 2025-09-20 22:53:50,109 django.server | "GET /api/ratings/ HTTP/1.1" 200 52
[WARNING] 2025-09-20 22:54:02,986 django.request | Not Found: /api/ratings/inception
[WARNING] 2025-09-20 22:54:02,987 django.server | "GET /api/ratings/inception HTTP/1.1" 404 3969
[INFO] 2025-09-20 22:54:16,766 django.server | "GET /api/ratings/ HTTP/1.1" 200 52
[INFO] 2025-09-20 22:55:54,124 django.server | "GET /api/ratings/add HTTP/1.1" 301 0
[WARNING] 2025-09-20 22:55:54,150 django.request | Method Not Allowed: /api/ratings/add/
[WARNING] 2025-09-20 22:55:54,152 django.server | "GET /api/ratings/add/ HTTP/1.1" 405 40
[INFO] 2025-09-20 22:58:43,861 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\views.py changed, reloading.
[INFO] 2025-09-20 22:58:44,908 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-20 22:59:12,516 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\urls.py changed, reloading.
[INFO] 2025-09-20 22:59:13,648 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-20 22:59:34,959 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\urls.py changed, reloading.
[INFO] 2025-09-20 22:59:36,196 django.utils.autoreload | Watching for file changes with StatReloader
[WARNING] 2025-09-20 22:59:42,910 django.request | Not Found: /api/ratings/add/
[WARNING] 2025-09-20 22:59:42,911 django.server | "GET /api/ratings/add/ HTTP/1.1" 404 3693
[INFO] 2025-09-20 22:59:53,909 django.server | "GET /api/ratings/ HTTP/1.1" 200 52
[INFO] 2025-09-20 23:01:03,873 django.server | "POST /api/token/ HTTP/1.1" 200 494
[WARNING] 2025-09-20 23:05:47,061 django.request | Forbidden: /api/ratings/
[WARNING] 2025-09-20 23:05:47,062 django.server | "POST /api/ratings/?Authorization=Bearer%20%20%20%20%20%22access%22:%20%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4Mzg5NzYzLCJpYXQiOjE3NTgzODk0NjMsImp0aSI6IjM1ZDgzMmQwMDdlODQzNTJhMmU4ZjAzOWE4ZWYxNDJkIiwidXNlcl9pZCI6IjI3OCJ9.sYzCk7sj7uOFpOduwHcHtqR9rWrWeeKPA3lgU2x4FIs%22%0A HTTP/1.1" 403 58
[WARNING] 2025-09-20 23:06:15,145 django.request | Forbidden: /api/ratings/
[WARNING] 2025-09-20 23:06:15,146 django.server | "POST /api/ratings/?Authorization=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4Mzg5NzYzLCJpYXQiOjE3NTgzODk0NjMsImp0aSI6IjM1ZDgzMmQwMDdlODQzNTJhMmU4ZjAzOWE4ZWYxNDJkIiwidXNlcl9pZCI6IjI3OCJ9.sYzCk7sj7uOFpOduwHcHtqR9rWrWeeKPA3lgU2x4FIs%0A HTTP/1.1" 403 58
[WARNING] 2025-09-20 23:11:36,924 django.request | Not Found: /api/gettoken/
[WARNING] 2025-09-20 23:11:36,925 django.server | "POST /api/gettoken/ HTTP/1.1" 404 3685
[INFO] 2025-09-20 23:12:15,986 django.server | "POST /api/token/ HTTP/1.1" 200 494
[WARNING] 2025-09-20 23:12:46,322 django.request | Forbidden: /api/ratings/
[WARNING] 2025-09-20 23:12:46,323 django.server | "POST /api/ratings/ HTTP/1.1" 403 58
[INFO] 2025-09-20 23:14:06,511 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movie_recommender\settings.py changed, reloading.
[INFO] 2025-09-20 23:14:07,740 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-20 23:14:11,013 django.server | "POST /api/ratings/ HTTP/1.1" 201 35
[INFO] 2025-09-20 23:14:22,681 django.server | "GET /api/ratings/ HTTP/1.1" 200 87
[INFO] 2025-09-21 12:18:15,550 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-21 12:20:15,904 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\urls.py changed, reloading.
[INFO] 2025-09-21 12:20:16,941 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-21 12:20:20,460 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\views.py changed, reloading.
[INFO] 2025-09-21 12:20:21,463 django.utils.autoreload | Watching for file changes with StatReloader
[INFO] 2025-09-21 12:20:23,122 django.utils.autoreload | C:\Users\vyshn\movie_recommender\movies\views.py changed, reloading.
[INFO] 2025-09-21 12:20:24,190 django.utils.autoreload | Watching for file changes with StatReloader
